In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\limar\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\limar\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from openpyxl) (2.0.0)

In [3]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2020-21&SeasonType=Regular%20Season&StatCategory=PTS'

In [4]:
r = requests.get(url=test_url).json()

In [5]:
table_headers = r['resultSet']['headers']

In [6]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201939,1,Stephen Curry,1610612744,GSW,63,2152,658,1365,0.482,337,801,0.421,362,395,0.916,29,316,345,363,77,8,213,119,2015,1855,1.70,0.36
1,203081,2,Damian Lillard,1610612757,POR,67,2398,602,1334,0.451,275,704,0.391,449,484,0.928,32,251,283,505,62,17,203,102,1928,1825,2.49,0.30
2,203999,3,Nikola Jokić,1610612743,DEN,72,2488,732,1293,0.566,92,237,0.388,342,394,0.868,205,575,780,599,95,48,222,192,1898,2585,2.70,0.43
3,203078,4,Bradley Beal,1610612764,WAS,60,2147,670,1382,0.485,130,373,0.349,408,459,0.889,72,211,283,265,69,22,187,140,1878,1567,1.42,0.37
4,1629029,5,Luka Dončić,1610612742,DAL,66,2262,647,1351,0.479,192,548,0.350,344,471,0.730,54,473,527,567,64,36,281,152,1830,1912,2.02,0.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,1628394,536,Anzejs Pasecniks,1610612764,WAS,1,6,0,1,0.000,0,1,0.000,0,0,0.000,1,0,1,1,0,0,5,2,0,-4,0.20,0.00
536,1630204,536,Ashton Hagans,1610612750,MIN,2,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,1,0,0,-1,0.00,0.00
537,204222,536,Greg Whittington,1610612743,DEN,4,12,0,3,0.000,0,2,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-3,0.00,0.00
538,203943,536,Noah Vonleh,1610612751,BKN,4,11,0,3,0.000,0,2,0.000,0,0,0.000,0,1,1,1,0,0,2,2,0,-3,0.50,0.00
539,1630266,536,Will Magnay,1610612740,NOP,1,3,0,1,0.000,0,1,0.000,0,0,0.000,0,0,0,0,0,0,1,1,0,-2,0.00,0.00

In [7]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
temp_df2 = pd.DataFrame({'Year':['2020-21' for i in range(len(temp_df1))],
                         'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2020-21,Regular%20Season,201939,1,Stephen Curry,1610612744,GSW,63,2152,658,1365,0.482,337,801,0.421,362,395,0.916,29,316,345,363,77,8,213,119,2015,1855,1.70,0.36
1,2020-21,Regular%20Season,203081,2,Damian Lillard,1610612757,POR,67,2398,602,1334,0.451,275,704,0.391,449,484,0.928,32,251,283,505,62,17,203,102,1928,1825,2.49,0.30
2,2020-21,Regular%20Season,203999,3,Nikola Jokić,1610612743,DEN,72,2488,732,1293,0.566,92,237,0.388,342,394,0.868,205,575,780,599,95,48,222,192,1898,2585,2.70,0.43
3,2020-21,Regular%20Season,203078,4,Bradley Beal,1610612764,WAS,60,2147,670,1382,0.485,130,373,0.349,408,459,0.889,72,211,283,265,69,22,187,140,1878,1567,1.42,0.37
4,2020-21,Regular%20Season,1629029,5,Luka Dončić,1610612742,DAL,66,2262,647,1351,0.479,192,548,0.350,344,471,0.730,54,473,527,567,64,36,281,152,1830,1912,2.02,0.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2020-21,Regular%20Season,1628394,536,Anzejs Pasecniks,1610612764,WAS,1,6,0,1,0.000,0,1,0.000,0,0,0.000,1,0,1,1,0,0,5,2,0,-4,0.20,0.00
536,2020-21,Regular%20Season,1630204,536,Ashton Hagans,1610612750,MIN,2,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,1,0,0,-1,0.00,0.00
537,2020-21,Regular%20Season,204222,536,Greg Whittington,1610612743,DEN,4,12,0,3,0.000,0,2,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-3,0.00,0.00
538,2020-21,Regular%20Season,203943,536,Noah Vonleh,1610612751,BKN,4,11,0,3,0.000,0,2,0.000,0,0,0.000,0,1,1,1,0,0,2,2,0,-3,0.50,0.00
539,2020-21,Regular%20Season,1630266,536,Will Magnay,1610612740,NOP,1,3,0,1,0.000,0,1,0.000,0,0,0.000,0,0,0,0,0,0,1,1,0,-2,0.00,0.00

In [8]:
del temp_df1, temp_df2, temp_df3

In [9]:
df_cols = ['Year', 'Season_type'] + table_headers

In [10]:
pd.DataFrame(columns = df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [11]:
headers = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': "Android",
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36'
}

In [12]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2020-21', '2021-22', '2022-23', '2023-24', '2024-25']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=' + y + '&SeasonType=' + s + '&StatCategory=PTS'
        r = requests.get(url=api_url, headers=headers).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                 'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
        df = pd.concat([df, temp_df3], axis=0)
        print(f'Finished scraping data for the {y} {s}.')
        lag = np.random.uniform(low=5,high=40)
        print(f'...wating {round(lag,1)} seconds')
        time.sleep(lag)

print(f'Processed completed! Total run time: {round((time.time()-begin_loop)/60,2)}')
df.to_excel('nba_play_data.xlsx', index=False, engine='openpyxl')

C:\Users\limar\AppData\Local\Temp\ipykernel_40308\3215021607.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Finished scraping data for the 2020-21 Regular%20Season.
...wating 5.8 seconds
Finished scraping data for the 2020-21 Playoffs.
...wating 15.7 seconds
Finished scraping data for the 2021-22 Regular%20Season.
...wating 7.6 seconds
Finished scraping data for the 2021-22 Playoffs.
...wating 17.8 seconds
Finished scraping data for the 2022-23 Regular%20Season.
...wating 27.5 seconds
Finished scraping data for the 2022-23 Playoffs.
...wating 19.0 seconds
Finished scraping data for the 2023-24 Regular%20Season.
...wating 14.8 seconds
Finished scraping data for the 2023-24 Playoffs.
...wating 36.7 seconds
Finished scraping data for the 2024-25 Regular%20Season.
...wating 6.2 seconds

C:\Users\limar\AppData\Local\Temp\ipykernel_40308\3215021607.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Finished scraping data for the 2024-25 Playoffs.
...wating 7.1 seconds
Processed completed! Total run time: 2.69