In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\limar\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\limar\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from openpyxl) (2.0.0)

In [3]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2018-19&SeasonType=Regular%20Season&StatCategory=PTS'

In [4]:
r = requests.get(url=test_url).json()

In [5]:
table_headers = r['resultSet']['headers']

In [6]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201935,1,James Harden,1610612745,HOU,78,2867,843,1909,0.442,378,1028,0.368,754,858,0.879,66,452,518,586,158,58,387,244,2818,2581,1.51,0.41
1,202331,2,Paul George,1610612760,OKC,77,2841,707,1614,0.438,292,757,0.386,453,540,0.839,105,523,628,318,170,34,205,214,2159,2110,1.55,0.83
2,202689,3,Kemba Walker,1610612766,CHA,82,2863,731,1684,0.434,260,731,0.356,380,450,0.844,52,309,361,484,102,34,211,131,2102,1849,2.29,0.48
3,203078,4,Bradley Beal,1610612764,WAS,82,3028,764,1609,0.475,209,596,0.351,362,448,0.808,89,322,411,448,121,58,224,226,2099,1982,2.00,0.54
4,203081,5,Damian Lillard,1610612757,POR,80,2838,681,1533,0.444,237,643,0.369,468,513,0.912,68,303,371,551,88,34,212,148,2067,2002,2.60,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,1628424,521,Kobi Simmons,1610612739,CLE,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
526,1627855,521,Okaro White,1610612764,WAS,3,6,0,2,0.000,0,2,0.000,0,0,0.000,1,1,2,0,0,0,0,0,0,0,0.00,0.00
527,1629093,521,Tyler Davis,1610612760,OKC,1,1,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,0,0,0,0,0,0,0,0.00,0.00
528,1627755,521,Tyler Ulis,1610612741,CHI,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
529,1629155,521,Zach Lofton,1610612765,DET,1,4,0,1,0.000,0,1,0.000,0,0,0.000,0,0,0,0,1,0,1,0,0,-1,0.00,1.00

In [7]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
temp_df2 = pd.DataFrame({'Year':['2018-19' for i in range(len(temp_df1))],
                         'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2018-19,Regular%20Season,201935,1,James Harden,1610612745,HOU,78,2867,843,1909,0.442,378,1028,0.368,754,858,0.879,66,452,518,586,158,58,387,244,2818,2581,1.51,0.41
1,2018-19,Regular%20Season,202331,2,Paul George,1610612760,OKC,77,2841,707,1614,0.438,292,757,0.386,453,540,0.839,105,523,628,318,170,34,205,214,2159,2110,1.55,0.83
2,2018-19,Regular%20Season,202689,3,Kemba Walker,1610612766,CHA,82,2863,731,1684,0.434,260,731,0.356,380,450,0.844,52,309,361,484,102,34,211,131,2102,1849,2.29,0.48
3,2018-19,Regular%20Season,203078,4,Bradley Beal,1610612764,WAS,82,3028,764,1609,0.475,209,596,0.351,362,448,0.808,89,322,411,448,121,58,224,226,2099,1982,2.00,0.54
4,2018-19,Regular%20Season,203081,5,Damian Lillard,1610612757,POR,80,2838,681,1533,0.444,237,643,0.369,468,513,0.912,68,303,371,551,88,34,212,148,2067,2002,2.60,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,2018-19,Regular%20Season,1628424,521,Kobi Simmons,1610612739,CLE,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
526,2018-19,Regular%20Season,1627855,521,Okaro White,1610612764,WAS,3,6,0,2,0.000,0,2,0.000,0,0,0.000,1,1,2,0,0,0,0,0,0,0,0.00,0.00
527,2018-19,Regular%20Season,1629093,521,Tyler Davis,1610612760,OKC,1,1,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,0,0,0,0,0,0,0,0.00,0.00
528,2018-19,Regular%20Season,1627755,521,Tyler Ulis,1610612741,CHI,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
529,2018-19,Regular%20Season,1629155,521,Zach Lofton,1610612765,DET,1,4,0,1,0.000,0,1,0.000,0,0,0.000,0,0,0,0,1,0,1,0,0,-1,0.00,1.00

In [8]:
del temp_df1, temp_df2, temp_df3

In [9]:
df_cols = ['Year', 'Season_type'] + table_headers

In [10]:
pd.DataFrame(columns = df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [11]:
headers = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': "Android",
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36'
}

In [12]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=' + y + '&SeasonType=' + s + '&StatCategory=PTS'
        r = requests.get(url=api_url, headers=headers).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                 'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
        df = pd.concat([df, temp_df3], axis=0)
        print(f'Finished scraping data for the {y} {s}.')
        lag = np.random.uniform(low=5,high=40)
        print(f'...wating {round(lag,1)} seconds')
        time.sleep(lag)

print(f'Processed completed! Total run time: {round((time.time()-begin_loop)/60,2)}')
df.to_excel('nba_play_data.xlsx', index=False, engine='openpyxl')

C:\Users\limar\AppData\Local\Temp\ipykernel_59884\2982016665.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Finished scraping data for the 2018-19 Regular%20Season.
...wating 22.7 seconds
Finished scraping data for the 2018-19 Playoffs.
...wating 16.6 seconds
Finished scraping data for the 2019-20 Regular%20Season.
...wating 33.7 seconds
Finished scraping data for the 2019-20 Playoffs.
...wating 13.1 seconds
Finished scraping data for the 2020-21 Regular%20Season.
...wating 21.2 seconds
Finished scraping data for the 2020-21 Playoffs.
...wating 6.7 seconds
Finished scraping data for the 2021-22 Regular%20Season.
...wating 29.6 seconds
Finished scraping data for the 2021-22 Playoffs.
...wating 8.8 seconds
Finished scraping data for the 2022-23 Regular%20Season.
...wating 20.5 seconds
Finished scraping data for the 2022-23 Playoffs.
...wating 30.0 seconds
Finished scraping data for the 2023-24 Regular%20Season.
...wating 22.3 seconds
Finished scraping data for the 2023-24 Playoffs.
...wating 28.8 seconds
Finished scraping data for the 2024-25 Regular%20Season.
...wating 33.8 seconds

C:\Users\limar\AppData\Local\Temp\ipykernel_59884\2982016665.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis=0)

Finished scraping data for the 2024-25 Playoffs.
...wating 23.0 seconds
Processed completed! Total run time: 5.32